FROM multiarch/alpine:aarch64-edge 

ENV TZ=Asia/Shanghai

RUN apk --no-cache --no-progress upgrade && \
  apk --no-cache --no-progress add perl curl bash iptables pcre openssl dnsmasq ipset iproute2 tzdata jq && \
  ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

COPY init.sh update.sh /
COPY ss-tproxy.conf v2ray.conf gfwlist.ext /sample_config/

RUN chmod +x /init.sh /update.sh && /update.sh

CMD ["/init.sh","daemon"]